name: CI
on:
  push:
    paths-ignore:
      - "README.md"

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: Setup dotnet
        uses: actions/setup-dotnet@v3
        with:
          global-json-file: "./global.json"
      - name: dotnet restore
        run: dotnet restore
      - name: dotnet tool restore
        run: dotnet tool restore
      - name: dotnet format
        run: dotnet format --verify-no-changes --no-restore
      - name: dotnet roslynator analyze
        run: dotnet roslynator analyze
      - name: dotnet build
        run: dotnet build --no-restore -warnaserror -clp:NoSummary
